/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitanteRouteImport } from './routes/solicitante'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CoordenadorRouteImport } from './routes/coordenador'
import { Route as ChefiaRouteImport } from './routes/chefia'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolicitanteIndexRouteImport } from './routes/solicitante.index'
import { Route as CoordenadorIndexRouteImport } from './routes/coordenador.index'
import { Route as ChefiaIndexRouteImport } from './routes/chefia.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SolicitanteNovaRouteImport } from './routes/solicitante.nova'
import { Route as SolicitanteMinhasRouteImport } from './routes/solicitante.minhas'
import { Route as CoordenadorTodasRouteImport } from './routes/coordenador.todas'
import { Route as CoordenadorRelatoriosRouteImport } from './routes/coordenador.relatorios'
import { Route as CoordenadorFaqRouteImport } from './routes/coordenador.faq'
import { Route as CoordenadorAcessosRouteImport } from './routes/coordenador.acessos'
import { Route as ChefiaRecursosRouteImport } from './routes/chefia.recursos'
import { Route as ChefiaPendentesRouteImport } from './routes/chefia.pendentes'
import { Route as ChefiaHistoricoRouteImport } from './routes/chefia.historico'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminMensageriaRouteImport } from './routes/admin.mensageria'
import { Route as AdminAdRouteImport } from './routes/admin.ad'
import { Route as AdminAcessosRouteImport } from './routes/admin.acessos'
import { Route as ChefiaAnaliseIdRouteImport } from './routes/chefia.analise.$id'
import { Route as ApiAuthGovbrCallbackRouteImport } from './routes/api/auth.govbr.callback'

const SolicitanteRoute = SolicitanteRouteImport.update({
  id: '/solicitante',
  path: '/solicitante',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenadorRoute = CoordenadorRouteImport.update({
  id: '/coordenador',
  path: '/coordenador',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefiaRoute = ChefiaRouteImport.update({
  id: '/chefia',
  path: '/chefia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitanteIndexRoute = SolicitanteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolicitanteRoute,
} as any)
const CoordenadorIndexRoute = CoordenadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordenadorRoute,
} as any)
const ChefiaIndexRoute = ChefiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChefiaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SolicitanteNovaRoute = SolicitanteNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => SolicitanteRoute,
} as any)
const SolicitanteMinhasRoute = SolicitanteMinhasRouteImport.update({
  id: '/minhas',
  path: '/minhas',
  getParentRoute: () => SolicitanteRoute,
} as any)
const CoordenadorTodasRoute = CoordenadorTodasRouteImport.update({
  id: '/todas',
  path: '/todas',
  getParentRoute: () => CoordenadorRoute,
} as any)
const CoordenadorRelatoriosRoute = CoordenadorRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => CoordenadorRoute,
} as any)
const CoordenadorFaqRoute = CoordenadorFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => CoordenadorRoute,
} as any)
const CoordenadorAcessosRoute = CoordenadorAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => CoordenadorRoute,
} as any)
const ChefiaRecursosRoute = ChefiaRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => ChefiaRoute,
} as any)
const ChefiaPendentesRoute = ChefiaPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => ChefiaRoute,
} as any)
const ChefiaHistoricoRoute = ChefiaHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ChefiaRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensageriaRoute = AdminMensageriaRouteImport.update({
  id: '/mensageria',
  path: '/mensageria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdRoute = AdminAdRouteImport.update({
  id: '/ad',
  path: '/ad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcessosRoute = AdminAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AdminRoute,
} as any)
const ChefiaAnaliseIdRoute = ChefiaAnaliseIdRouteImport.update({
  id: '/analise/$id',
  path: '/analise/$id',
  getParentRoute: () => ChefiaRoute,
} as any)
const ApiAuthGovbrCallbackRoute = ApiAuthGovbrCallbackRouteImport.update({
  id: '/api/auth/govbr/callback',
  path: '/api/auth/govbr/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chefia': typeof ChefiaRouteWithChildren
  '/coordenador': typeof CoordenadorRouteWithChildren
  '/faq': typeof FaqRoute
  '/solicitante': typeof SolicitanteRouteWithChildren
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/ad': typeof AdminAdRoute
  '/admin/mensageria': typeof AdminMensageriaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/chefia/historico': typeof ChefiaHistoricoRoute
  '/chefia/pendentes': typeof ChefiaPendentesRoute
  '/chefia/recursos': typeof ChefiaRecursosRoute
  '/coordenador/acessos': typeof CoordenadorAcessosRoute
  '/coordenador/faq': typeof CoordenadorFaqRoute
  '/coordenador/relatorios': typeof CoordenadorRelatoriosRoute
  '/coordenador/todas': typeof CoordenadorTodasRoute
  '/solicitante/minhas': typeof SolicitanteMinhasRoute
  '/solicitante/nova': typeof SolicitanteNovaRoute
  '/admin/': typeof AdminIndexRoute
  '/chefia/': typeof ChefiaIndexRoute
  '/coordenador/': typeof CoordenadorIndexRoute
  '/solicitante/': typeof SolicitanteIndexRoute
  '/chefia/analise/$id': typeof ChefiaAnaliseIdRoute
  '/api/auth/govbr/callback': typeof ApiAuthGovbrCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/ad': typeof AdminAdRoute
  '/admin/mensageria': typeof AdminMensageriaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/chefia/historico': typeof ChefiaHistoricoRoute
  '/chefia/pendentes': typeof ChefiaPendentesRoute
  '/chefia/recursos': typeof ChefiaRecursosRoute
  '/coordenador/acessos': typeof CoordenadorAcessosRoute
  '/coordenador/faq': typeof CoordenadorFaqRoute
  '/coordenador/relatorios': typeof CoordenadorRelatoriosRoute
  '/coordenador/todas': typeof CoordenadorTodasRoute
  '/solicitante/minhas': typeof SolicitanteMinhasRoute
  '/solicitante/nova': typeof SolicitanteNovaRoute
  '/admin': typeof AdminIndexRoute
  '/chefia': typeof ChefiaIndexRoute
  '/coordenador': typeof CoordenadorIndexRoute
  '/solicitante': typeof SolicitanteIndexRoute
  '/chefia/analise/$id': typeof ChefiaAnaliseIdRoute
  '/api/auth/govbr/callback': typeof ApiAuthGovbrCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chefia': typeof ChefiaRouteWithChildren
  '/coordenador': typeof CoordenadorRouteWithChildren
  '/faq': typeof FaqRoute
  '/solicitante': typeof SolicitanteRouteWithChildren
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/ad': typeof AdminAdRoute
  '/admin/mensageria': typeof AdminMensageriaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/chefia/historico': typeof ChefiaHistoricoRoute
  '/chefia/pendentes': typeof ChefiaPendentesRoute
  '/chefia/recursos': typeof ChefiaRecursosRoute
  '/coordenador/acessos': typeof CoordenadorAcessosRoute
  '/coordenador/faq': typeof CoordenadorFaqRoute
  '/coordenador/relatorios': typeof CoordenadorRelatoriosRoute
  '/coordenador/todas': typeof CoordenadorTodasRoute
  '/solicitante/minhas': typeof SolicitanteMinhasRoute
  '/solicitante/nova': typeof SolicitanteNovaRoute
  '/admin/': typeof AdminIndexRoute
  '/chefia/': typeof ChefiaIndexRoute
  '/coordenador/': typeof CoordenadorIndexRoute
  '/solicitante/': typeof SolicitanteIndexRoute
  '/chefia/analise/$id': typeof ChefiaAnaliseIdRoute
  '/api/auth/govbr/callback': typeof ApiAuthGovbrCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chefia'
    | '/coordenador'
    | '/faq'
    | '/solicitante'
    | '/admin/acessos'
    | '/admin/ad'
    | '/admin/mensageria'
    | '/admin/usuarios'
    | '/chefia/historico'
    | '/chefia/pendentes'
    | '/chefia/recursos'
    | '/coordenador/acessos'
    | '/coordenador/faq'
    | '/coordenador/relatorios'
    | '/coordenador/todas'
    | '/solicitante/minhas'
    | '/solicitante/nova'
    | '/admin/'
    | '/chefia/'
    | '/coordenador/'
    | '/solicitante/'
    | '/chefia/analise/$id'
    | '/api/auth/govbr/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/admin/acessos'
    | '/admin/ad'
    | '/admin/mensageria'
    | '/admin/usuarios'
    | '/chefia/historico'
    | '/chefia/pendentes'
    | '/chefia/recursos'
    | '/coordenador/acessos'
    | '/coordenador/faq'
    | '/coordenador/relatorios'
    | '/coordenador/todas'
    | '/solicitante/minhas'
    | '/solicitante/nova'
    | '/admin'
    | '/chefia'
    | '/coordenador'
    | '/solicitante'
    | '/chefia/analise/$id'
    | '/api/auth/govbr/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chefia'
    | '/coordenador'
    | '/faq'
    | '/solicitante'
    | '/admin/acessos'
    | '/admin/ad'
    | '/admin/mensageria'
    | '/admin/usuarios'
    | '/chefia/historico'
    | '/chefia/pendentes'
    | '/chefia/recursos'
    | '/coordenador/acessos'
    | '/coordenador/faq'
    | '/coordenador/relatorios'
    | '/coordenador/todas'
    | '/solicitante/minhas'
    | '/solicitante/nova'
    | '/admin/'
    | '/chefia/'
    | '/coordenador/'
    | '/solicitante/'
    | '/chefia/analise/$id'
    | '/api/auth/govbr/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChefiaRoute: typeof ChefiaRouteWithChildren
  CoordenadorRoute: typeof CoordenadorRouteWithChildren
  FaqRoute: typeof FaqRoute
  SolicitanteRoute: typeof SolicitanteRouteWithChildren
  ApiAuthGovbrCallbackRoute: typeof ApiAuthGovbrCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitante': {
      id: '/solicitante'
      path: '/solicitante'
      fullPath: '/solicitante'
      preLoaderRoute: typeof SolicitanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenador': {
      id: '/coordenador'
      path: '/coordenador'
      fullPath: '/coordenador'
      preLoaderRoute: typeof CoordenadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefia': {
      id: '/chefia'
      path: '/chefia'
      fullPath: '/chefia'
      preLoaderRoute: typeof ChefiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitante/': {
      id: '/solicitante/'
      path: '/'
      fullPath: '/solicitante/'
      preLoaderRoute: typeof SolicitanteIndexRouteImport
      parentRoute: typeof SolicitanteRoute
    }
    '/coordenador/': {
      id: '/coordenador/'
      path: '/'
      fullPath: '/coordenador/'
      preLoaderRoute: typeof CoordenadorIndexRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/chefia/': {
      id: '/chefia/'
      path: '/'
      fullPath: '/chefia/'
      preLoaderRoute: typeof ChefiaIndexRouteImport
      parentRoute: typeof ChefiaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/solicitante/nova': {
      id: '/solicitante/nova'
      path: '/nova'
      fullPath: '/solicitante/nova'
      preLoaderRoute: typeof SolicitanteNovaRouteImport
      parentRoute: typeof SolicitanteRoute
    }
    '/solicitante/minhas': {
      id: '/solicitante/minhas'
      path: '/minhas'
      fullPath: '/solicitante/minhas'
      preLoaderRoute: typeof SolicitanteMinhasRouteImport
      parentRoute: typeof SolicitanteRoute
    }
    '/coordenador/todas': {
      id: '/coordenador/todas'
      path: '/todas'
      fullPath: '/coordenador/todas'
      preLoaderRoute: typeof CoordenadorTodasRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/coordenador/relatorios': {
      id: '/coordenador/relatorios'
      path: '/relatorios'
      fullPath: '/coordenador/relatorios'
      preLoaderRoute: typeof CoordenadorRelatoriosRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/coordenador/faq': {
      id: '/coordenador/faq'
      path: '/faq'
      fullPath: '/coordenador/faq'
      preLoaderRoute: typeof CoordenadorFaqRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/coordenador/acessos': {
      id: '/coordenador/acessos'
      path: '/acessos'
      fullPath: '/coordenador/acessos'
      preLoaderRoute: typeof CoordenadorAcessosRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/chefia/recursos': {
      id: '/chefia/recursos'
      path: '/recursos'
      fullPath: '/chefia/recursos'
      preLoaderRoute: typeof ChefiaRecursosRouteImport
      parentRoute: typeof ChefiaRoute
    }
    '/chefia/pendentes': {
      id: '/chefia/pendentes'
      path: '/pendentes'
      fullPath: '/chefia/pendentes'
      preLoaderRoute: typeof ChefiaPendentesRouteImport
      parentRoute: typeof ChefiaRoute
    }
    '/chefia/historico': {
      id: '/chefia/historico'
      path: '/historico'
      fullPath: '/chefia/historico'
      preLoaderRoute: typeof ChefiaHistoricoRouteImport
      parentRoute: typeof ChefiaRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensageria': {
      id: '/admin/mensageria'
      path: '/mensageria'
      fullPath: '/admin/mensageria'
      preLoaderRoute: typeof AdminMensageriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad': {
      id: '/admin/ad'
      path: '/ad'
      fullPath: '/admin/ad'
      preLoaderRoute: typeof AdminAdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/acessos': {
      id: '/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AdminAcessosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chefia/analise/$id': {
      id: '/chefia/analise/$id'
      path: '/analise/$id'
      fullPath: '/chefia/analise/$id'
      preLoaderRoute: typeof ChefiaAnaliseIdRouteImport
      parentRoute: typeof ChefiaRoute
    }
    '/api/auth/govbr/callback': {
      id: '/api/auth/govbr/callback'
      path: '/api/auth/govbr/callback'
      fullPath: '/api/auth/govbr/callback'
      preLoaderRoute: typeof ApiAuthGovbrCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAcessosRoute: typeof AdminAcessosRoute
  AdminAdRoute: typeof AdminAdRoute
  AdminMensageriaRoute: typeof AdminMensageriaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcessosRoute: AdminAcessosRoute,
  AdminAdRoute: AdminAdRoute,
  AdminMensageriaRoute: AdminMensageriaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChefiaRouteChildren {
  ChefiaHistoricoRoute: typeof ChefiaHistoricoRoute
  ChefiaPendentesRoute: typeof ChefiaPendentesRoute
  ChefiaRecursosRoute: typeof ChefiaRecursosRoute
  ChefiaIndexRoute: typeof ChefiaIndexRoute
  ChefiaAnaliseIdRoute: typeof ChefiaAnaliseIdRoute
}

const ChefiaRouteChildren: ChefiaRouteChildren = {
  ChefiaHistoricoRoute: ChefiaHistoricoRoute,
  ChefiaPendentesRoute: ChefiaPendentesRoute,
  ChefiaRecursosRoute: ChefiaRecursosRoute,
  ChefiaIndexRoute: ChefiaIndexRoute,
  ChefiaAnaliseIdRoute: ChefiaAnaliseIdRoute,
}

const ChefiaRouteWithChildren =
  ChefiaRoute._addFileChildren(ChefiaRouteChildren)

interface CoordenadorRouteChildren {
  CoordenadorAcessosRoute: typeof CoordenadorAcessosRoute
  CoordenadorFaqRoute: typeof CoordenadorFaqRoute
  CoordenadorRelatoriosRoute: typeof CoordenadorRelatoriosRoute
  CoordenadorTodasRoute: typeof CoordenadorTodasRoute
  CoordenadorIndexRoute: typeof CoordenadorIndexRoute
}

const CoordenadorRouteChildren: CoordenadorRouteChildren = {
  CoordenadorAcessosRoute: CoordenadorAcessosRoute,
  CoordenadorFaqRoute: CoordenadorFaqRoute,
  CoordenadorRelatoriosRoute: CoordenadorRelatoriosRoute,
  CoordenadorTodasRoute: CoordenadorTodasRoute,
  CoordenadorIndexRoute: CoordenadorIndexRoute,
}

const CoordenadorRouteWithChildren = CoordenadorRoute._addFileChildren(
  CoordenadorRouteChildren,
)

interface SolicitanteRouteChildren {
  SolicitanteMinhasRoute: typeof SolicitanteMinhasRoute
  SolicitanteNovaRoute: typeof SolicitanteNovaRoute
  SolicitanteIndexRoute: typeof SolicitanteIndexRoute
}

const SolicitanteRouteChildren: SolicitanteRouteChildren = {
  SolicitanteMinhasRoute: SolicitanteMinhasRoute,
  SolicitanteNovaRoute: SolicitanteNovaRoute,
  SolicitanteIndexRoute: SolicitanteIndexRoute,
}

const SolicitanteRouteWithChildren = SolicitanteRoute._addFileChildren(
  SolicitanteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChefiaRoute: ChefiaRouteWithChildren,
  CoordenadorRoute: CoordenadorRouteWithChildren,
  FaqRoute: FaqRoute,
  SolicitanteRoute: SolicitanteRouteWithChildren,
  ApiAuthGovbrCallbackRoute: ApiAuthGovbrCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
